function varargout = histGate_boundSet_dlg(stats)
handles.figure = figure('Visible','off','MenuBar','None','NumberTitle','off',...
                        'Toolbar','none','HandleVisibility','callback','Resize','off',...
                        'Color',get(0,'defaultuicontrolbackgroundcolor'),...
                        'name','Set boundaries','WindowStyle','modal',...
                        'Position',[520 714 316 100]);
handles.firstParam = uicontrol('Parent',handles.figure,'Style','popupmenu','String',...
    {'Mean','Median','Mode','Min','Max','STD','Variance','CV','CV^2','Var/Mean'},...
    'Position',[14 60 99 25],'BackgroundColor','White','HandleVisibility','callback','Callback',@changeMade_callback);
handles.firstParamText = uicontrol('Parent',handles.figure,'Style','text','String',...
    num2str(stats(1)),'Position',[14 35 99 25],'HandleVisibility','callback','ForegroundColor','Blue');
handles.text1 = uicontrol('Parent',handles.figure,'Style','text','string','±','FontSize',12,...
    'Position',[121 62 14 22],'HandleVisibility','callback');
handles.percent = uicontrol('Parent',handles.figure,'Style','edit','string','5','UserData',5,...
    'Position',[139 62 30 22],'BackgroundColor','White','HandleVisibility','callback',...
    'Callback',@changeMade_callback);
handles.text2 = uicontrol('Parent',handles.figure,'Style','text','string','% of','HorizontalAlignment','left',...
    'Position',[170 66 28 14],'HandleVisibility','callback'); 
handles.secondParam = uicontrol('Parent',handles.figure,'Style','popupmenu','String',...
    {'Mean','Median','Mode','Min','Max','STD','Variance','CV','CV^2','Var/Mean'},...
    'Position',[200 60 99 25],'BackgroundColor','White','HandleVisibility','callback','Callback',@changeMade_callback);
handles.secondParamText = uicontrol('Parent',handles.figure,'Style','text','ForegroundColor','Blue','String',...
    num2str(stats(1)*get(handles.percent,'UserData')/100),'Position',[150 35 99 25],'HandleVisibility','callback');
handles.cancel = uicontrol('Parent',handles.figure,'String','Cancel',...
	'Position',[14 12 62 22],'HandleVisibility','callback','Callback',@cancel_callback); 
handles.ok = uicontrol('Parent',handles.figure,'String','OK',...
	'Position',[231 12 68 22],'HandleVisibility','callback','Callback',@ok_callback); 
varargout{1} = 0;
uiwait(handles.figure);

function changeMade_callback(hObject,eventdata)%#ok
if hObject == handles.percent
    number = str2double(get(hObject,'String'));
    if isnan(number) || number<=0 || number > 100
        set(hObject,'String',num2str(get(hObject,'UserData')));
    else
        set(hObject,'String',num2str(number),'UserData',number);
    end
end
set(handles.firstParamText,'String',num2str(stats(get(handles.firstParam,'Value'))));
set(handles.secondParamText,'String',num2str(stats(get(handles.secondParam,'Value'))*get(handles.percent,'UserData')/100));
end
function ok_callback(hObject,eventdata)%#ok
varargout{1} = {get(handles.firstParam,'Value'),get(handles.percent,'UserData'),get(handles.secondParam,'Value')};
uiresume(handles.figure);
delete(handles.figure);
end
function cancel_callback(hObject,eventdata)%#ok
uiresume(handles.figure);
delete(handles.figure);
end
end