function varargout = isolineParam_dlg(xAxis,yAxis,xBins,yBins,isolineNo)

handles.figure = figure('visible','off','MenuBar','None','NumberTitle','off',...
                        'Toolbar','none','HandleVisibility','callback','Resize','off',...
                        'Color',get(0,'defaultuicontrolbackgroundcolor'),...
                        'name','Isol. params.','WindowStyle','modal',...
                        'Position',[520 634 250 168]);
handles.text1 = uicontrol('Parent',handles.figure,'Style','text',...
          'Position',[10 145 89 14],...
          'String','1. Number of bins:');
handles.xAxis = uicontrol('Parent',handles.figure,'Style','text',...
          'Position',[47 118 80 16],...
          'String',[xAxis,' : '],'HorizontalAlignment','right');
handles.yAxis = uicontrol('Parent',handles.figure,'Style','text',...
          'Position',[47 90 80 16],...
          'String',[yAxis,' : '],'HorizontalAlignment','right');
handles.xBins = uicontrol('Parent',handles.figure,'Style','edit',...
          'Position',[130 115 53 22],'BackgroundColor','White',...
          'String',num2str(xBins),'userData',xBins,...
          'Callback',@change_callback);
handles.yBins = uicontrol('Parent',handles.figure,'Style','edit',...
          'Position',[130 87 53 22],'BackgroundColor','White',...
          'String',num2str(yBins),'UserData',yBins,...
          'Callback',@change_callback); 
handles.text1 = uicontrol('Parent',handles.figure,'Style','text',...
          'Position',[10 54 150 14],...
          'String','2. Max. number of isolines:');
handles.isolineNo = uicontrol('Parent',handles.figure,'Style','edit',...
          'Position',[130 50 53 22],'BackgroundColor','White',...
          'String',num2str(isolineNo),'UserData',isolineNo,...
          'Callback',@change_callback);
handles.cancel = uicontrol('Parent',handles.figure,...
          'Position',[15 11 68 22],...
          'String','Cancel','Callback',@cancel_callback);
handles.ok = uicontrol('Parent',handles.figure,...
          'Position',[113 11 68 22],...
          'String','OK','Callback',@ok_callback);      
varargout{1} = 0;
set(handles.figure,'Visible','on');
uiwait(handles.figure);

function change_callback(hObject,eventdata)%#ok
newNumber = str2double(get(hObject,'String'));
if isnan(newNumber) || newNumber < 1
    set(hObject,'String',get(hObject,'UserData'));
else
    set(hObject,'String',num2str(newNumber),'UserData',newNumber);
end
end
function ok_callback(hObject,eventdata)%#ok
newXbins = str2double(get(handles.xBins,'String'));
newYbins = str2double(get(handles.yBins,'String'));
newIsolineNo = str2double(get(handles.isolineNo,'String'));
if newXbins ~= xBins || newYbins ~= yBins || newIsolineNo ~= isolineNo
    varargout{1} = [newXbins,newYbins,newIsolineNo];
end
uiresume(handles.figure);
delete(handles.figure);
end
function cancel_callback(hObject,eventdata)%#ok
uiresume(handles.figure);
delete(handles.figure);
end
end