function varargout = logicalGate_dlg(names,name,color)

handles.figure = figure('Visible','off','MenuBar','None','NumberTitle','off',...
                        'Toolbar','none','HandleVisibility','callback','Resize','off',...
                        'Color',get(0,'defaultuicontrolbackgroundcolor'),...
                        'name','Logical gate',...
                        'Position',[520 653 198 148]);
handles.text = uicontrol('Style','text','parent',handles.figure,...
                        'String','1. Specify logical gate name:',...
                        'HandleVisibility','Callback',...
                        'Position',[27 118 144 14]);
handles.name = uicontrol('Style','edit','parent',handles.figure,...
                        'String',name,'UserData',name,'BackgroundColor','white',...
                        'HandleVisibility','Callback',...
                        'Position',[15 86 168 20],'Callback',@name_callback);
handles.color = uicontrol('parent',handles.figure,...
                        'String','2. Choose Color','BackgroundColor',color,...
                        'HandleVisibility','Callback',...
                        'Position',[53 53 93 22],'Callback',@color_callback);
handles.cancel = uicontrol('parent',handles.figure,...
                        'String','Cancel',...
                        'HandleVisibility','Callback',...
                        'Position',[15 16 69 22],'Callback',@cancel_callback);
handles.ok = uicontrol('parent',handles.figure,...
                        'String','OK',...
                        'HandleVisibility','Callback',...
                        'Position',[114 16 69 22],'Callback',@ok_callback);
uicontrol(handles.ok);
varargout{1} = 0;
uiwait(handles.figure);

function ok_callback(hObject,eventdata)%#ok
varargout{1} = {get(handles.name,'UserData'),get(handles.color,'BackgroundColor')};    
uiresume(handles.figure);
delete(handles.figure);    
end
function cancel_callback(hObject,eventdata)%#ok
uiresume(handles.figure);
delete(handles.figure);
end
function name_callback(hObject,eventdata)%#ok
name = get(hObject,'String');
if isempty(name) 
    set(hObject,'String',get(hObject,'UserData'));
elseif ~isempty(find(ismember(name,names),1))
    errordlg('Gate in that name already exists','Error','replace');
    set(hObject,'String',get(hObject,'UserData'));
else
    set(hObject,'UserData',name);
end
end
function color_callback(hObject,eventdata)%#ok.
color = uisetcolor;
if ~isequal(color,0)
    set(hObject,'BackgroundColor',color);
end
end
end