function varargout = subplotsFigureTool_semiAutoColor_dlg(varargin)

handles.figure = figure('Visible','off','MenuBar','None','NumberTitle','off',...
                        'Toolbar','none','HandleVisibility','callback',...
                        'Color',get(0,'defaultuicontrolbackgroundcolor'),...
                        'Name','Set color sequence',...
                        'Position',[520 454 231 346],'Resize','off');             
handles.text = uicontrol('Parent',handles.figure,'Style','Text',...
                         'HandleVisibility','Callback',...
                         'String','Choose a sequence of files:',...
                         'Position',[27 313 164 14]);
handles.listbox = uicontrol('Parent',handles.figure,'Style','listbox',...
                            'HandleVisibility','Callback',...
                            'String',varargin{1,1},'BackgroundColor','white',...
                            'Position',[30 95 171 214],'Max',2);
handles.chooseColorPanel = uipanel('Parent',handles.figure,...
                                   'HandleVisibility','Callback',...
                                   'BorderType','none','units','pixels',...
                                   'Position',[56 49 119 46]);
handles.text2 = uicontrol('Parent',handles.chooseColorPanel,'Style','Text',...
                         'HandleVisibility','Callback',...
                         'String','Choose base color:',...
                         'Position',[8 23 97 16]);
handles.red = uicontrol('Style','toggleButton','Parent',handles.chooseColorPanel,...
                        'String',' ','BackgroundColor',[1 0 0],...
                        'HandleVisibility','callback',...
                        'Position',[9 4 15 16]);
handles.yellow = uicontrol('Style','toggleButton','Parent',handles.chooseColorPanel,...
                           'String',' ','BackgroundColor',[1 1 0],...
                           'HandleVisibility','callback',...
                           'Position',[25 4 15 16]);
handles.green = uicontrol('Style','toggleButton','Parent',handles.chooseColorPanel,...
                          'String',' ','BackgroundColor',[0 1 0],...
                          'HandleVisibility','callback',...
                          'Position',[41 4 15 16]);
handles.cyan = uicontrol('Style','toggleButton','Parent',handles.chooseColorPanel,...
                         'String',' ','BackgroundColor',[0 1 1],...
                         'HandleVisibility','callback',...
                         'Position',[57 4 15 16]);
handles.blue = uicontrol('Style','toggleButton','Parent',handles.chooseColorPanel,...
                         'String',' ','BackgroundColor',[0 0 1],...
                         'HandleVisibility','callback',...
                         'Position',[74 4 15 16],'Value',1);
handles.magenta = uicontrol('Style','toggleButton','Parent',handles.chooseColorPanel,...
                            'String',' ','BackgroundColor',[1 0 1],...
                            'HandleVisibility','callback',...
                            'Position',[91 4 15 16]);
handles.ok = uicontrol('Style','pushbutton','Parent',handles.figure,...
                       'String','OK',...
                       'HandleVisibility','callback',...
                       'Position',[144 16 68 22]);
handles.cancel = uicontrol('Style','pushbutton','Parent',handles.figure,...
                       'String','Cancel',...
                       'HandleVisibility','callback',...
                       'Position',[16 16 68 22]);

set([handles.red,handles.yellow,handles.green,handles.cyan,handles.blue,handles.magenta],...
                                    'Callback',             @colorChange_callback);
set(handles.ok,                     'Callback',             @ok_callback);
set(handles.cancel,                 'Callback',             @(~,~) delete(handles.figure));
    
varargout{1} = 0;
uiwait(handles.figure);

function colorChange_callback(hObject,eventData)%#ok
set([handles.red,handles.yellow,handles.green,handles.cyan,handles.blue,handles.magenta],...
	'Value',0);
set(hObject,'Value',1);
end
function ok_callback(hObject,eventData)%#ok
color = get(findobj([handles.red,handles.yellow,handles.green,handles.cyan,handles.blue,handles.magenta],...
            'flat','Value',1),'BackgroundColor');
varargout{1} = {get(handles.listbox,'Value'),color};
uiresume(handles.figure);
delete(handles.figure);
end
end